checks:
    php: true
filter:
    excluded_paths:
        - 'UnitTest/*'
        - 'IntegrationTest/*'
        - 'TestApp/bootstrap.php'
        - 'TestApp/index.php'
        - 'TestApp/app/*'
        - 'TestApp/app/*'
        - '**/*/Test/*'
        - '**/*/Modules/*'
tools:
    external_code_coverage:
        timeout: 2400
    php_code_coverage:
        enabled: false
    php_code_sniffer:
        config:
            standard: 'PSR2'
        filter:
            excluded_paths:
                - 'UnitTest/*'
                - 'IntegrationTest/*'
                - 'TestApp/bootstrap.php'
                - 'TestApp/index.php'
                - 'TestApp/app/*'
                - 'TestApp/app/*'
                - '**/*/Test/*'
                - '**/*/Modules/*'
    php_cpd:
        excluded_dirs:
            - 'UnitTest/*'
            - 'IntegrationTest/*'
            - 'TestApp/bootstrap.php'
            - 'TestApp/index.php'
            - 'TestApp/app/*'
            - 'TestApp/app/*'
            - '**/*/Test/*'
            - '**/*/Modules/*'
    php_cs_fixer:
        config:
            level: psr2
        filter:
            excluded_paths:
                - 'UnitTest/*'
                - 'IntegrationTest/*'
                - 'TestApp/bootstrap.php'
                - 'TestApp/index.php'
                - 'TestApp/app/*'
                - 'TestApp/app/*'
                - '**/*/Test/*'
                - '**/*/Modules/*'
    php_mess_detector:
        config:
            rulesets:
                - codesize
                - unusedcode
                - naming
                - design
            naming_rules:
                short_variable: { minimum: 2 }
        filter:
            excluded_paths:
                - 'UnitTest/*'
                - 'IntegrationTest/*'
                - 'TestApp/bootstrap.php'
                - 'TestApp/index.php'
                - 'TestApp/app/*'
                - 'TestApp/app/*'
                - '**/*/Test/*'
                - '**/*/Modules/*'
