sudo: required

services:
  - docker

language: php

before_script:
  - docker run --name test-mysql -p 13306:3306 -e MYSQL_DATABASE=sandbox -e MYSQL_USER=mysql -e MYSQL_PASSWORD=mysql -e MYSQL_ROOT_PASSWORD=root -d webstream/mysql
  - docker run --name test-postgres -p 15432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -d webstream/postgres
  - docker run --name test-php-apache -itd -p 8080:80 --link test-mysql:mysql --link test-postgres:postgres -v /home/travis/build/webstream-framework/Test/TestApp:/var/www/html webstream/php-apache
  - docker ps
  - docker sudo docker exec -it test-php-apache php -m
  - composer install && cd TestApp && composer install && cd ..
  - touch TestApp/log/webstream.test.log && chmod 777 -R TestApp/log

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter

php:
  - 7.0

addons:
  code_climate:
    repo_token:
      secure: "XXApNH4cUVWDB/45Fz2tzceKM1RHWVj6BCCDgOYMpw58WWlfQyzakQMsg8kLd5qxxVqv89NlgWNPsjCSI2loxxWstQbdpT9uzs/zYRWe3s/HpPmRasmOYLc+wR7uMmdMFHBrdRO9FMY99g7YNSnhDyriG8VT+kdbDHvComF2N/YYC2IO2iFrqQ441wWyVLvv1Fh7vjMjDB+hiwfyDnEJ+ghUZeKzygM665hCebAXcHEEwCjqYsjDYF6sSqeP69AwI7uzIcG8gNW2Kn31p58MN+7f192nqsY7zdcrUUlAKPq2/x2GEn3KcttBzL2+kH+aG2QoHlMFjvn2px8guqY/+09P/B1B48HPTwLp3BejyDb615Ih24MGRKcy9adWQ5zrlQCztG3dZkKgWGg5SbIDAn8dS5kx3i1mpM1nfFgUoPzIb8MZxTB9vHO2nSgrR6Zl+O3uPplkJmHejqyCEFVGI55NLXL6HuFfTP7ZkDA7lHJHrknCrkY0bp8hU8cpHB3R8bZan0B/4ElvXxeJbCWi27SBPDMdBI7PS17pEVhmI0jVJK2hWYYov38Y82Il2RiTuwt4Y9ALuF+WcT9rmTtKPOZtbYLc1eD+QhmS0w1wrraGtMjmni4pfS+edrsGM4lkAJvMi2n78hqHUMmF5k9odi7gFZmMhzJTX3AFSPphNhU="

notifications:
  slack:
    secure: tobcQWs5nYA4dk9FkGsYEc7NKTOfwwB43eu4mAa6Iqmr5rRF8fpj0iebwfTrkXBcOCbqfwbr4OMWQ2Dq5PuAp0NlCkHGBr6QH4COzjopO/qOSllVkxnlwi/SKYLcrLdtWdwUCJRbpp72UWCJgq/mhP1ksJf6TtlzpCc5fkO0gxJNUvMb/uUqKUWebHK4bNtNTWE5ffy7Mnxh33Ad+CTV0bqPRuRgwkh0kR4lv/83ew+EzXkxzFPppy4BJMtuBqSDx2RFsY5d8ejwVTJzVz1JLMAKzvrf5VXU+EndeaIx68zDT0bwwyq2H07ovVrL4CTkbI2a4yJDZHPhLee9JQ1fVIS7idV30ChY8drsI1xQDKYkE/vaXjlKE/cB6uOE245X+Ht6uhILTJpwjHSu0CHX3RdyWSXnSg0AsaPZN2g/58W9CzfAK9w6tgVPtxhAE81L+7De9BehEfyUfDN5EN1o4C1KWH9LLw8z6Ha19DG2d/xhJOWSMFu64TiwkuQ3lb14x/R/bcO8rJpxcpnTp10r6NIRAMJKnbMiOmmzgu7EONiUPkjIFuf57p7/rCjGLCqE8OYOhh/xt1sWzn0T17ztzKTlhoJtBq6pvkbRY8OdGsfjUvlvbEJG9zi2qqv2d8DLhGXtFWu39+A1YfEwrdi/BANuLx7vLYHYRczjveyWAlw=
