language: php

before_script:
  - composer install
  - cd TestApp && composer install && cd ..

script:
  - phpunit --configuration phpunit.xml --coverage-clover reports/clover.xml UnitTest

php:
  - 7.0
