version: '2'
services:
  mysql:
    image: webstream/mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=sandbox
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
  postgres:
    image: webstream/postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  php-apache:
    image: webstream/php-apache
    container_name: php-apache
    ports:
      - 80:80
    links:
      - mysql:mysql
      - postgres:postgres
