'/controller/ok': 'test_controller#test1'
'/controller/parent_class_method_access': 'test_child#test1'
'/controller/upper_method/1': 'test_method_case#upper_case'
'/controller/upper_method/2': 'test_method_case#uppercase'
'/controller/lower_method/1': 'test_method_case#lower_case'
'/controller/lower_method/2': 'test_method_case#lowercase'
'/controller/error/controller_method_noexist': 'test_controller#notFound'
'/service/ok': 'test_service#test1'
'/service/error/service_method_noexist': 'test_service#notFound'
'/service/error/service_class_noexist_and_model_class_noexist': "test_no_service_class_no_model_class#test1"
'/model/ok': 'test_model#test1'
'/model/service_class_noexist_and_model_class_exist': 'test_no_service_class_exist_model#test1'
'/model/mysql/direct_select_query': 'test_mysql#direct_select_query'
'/model/mysql/annotation_select_query': 'test_mysql#annotation_select_query'
'/model/mysql/direct_insert_query': 'test_mysql#direct_insert_query'
'/model/mysql/annotation_insert_query': 'test_mysql#annotation_insert_query'
'/model/mysql/direct_update_query': 'test_mysql#direct_update_query'
'/model/mysql/annotation_update_query': 'test_mysql#annotation_update_query'
'/model/mysql/direct_delete_query': 'test_mysql#direct_delete_query'
'/model/mysql/annotation_delete_query': 'test_mysql#annotation_delete_query'
'/model/mysql/yml': 'test_mysql_yml#direct_select_query'
'/model/mysql/entity_mapping1': 'test_mysql#entity_mapping1'
'/model/mysql/entity_mapping2': 'test_mysql#entity_mapping2'
'/model/mysql/entity_mapping_joined_table': 'test_mysql#entity_mapping_joined_table'
'/model/mysql/entity_mapping_column_alias': 'test_mysql#entity_mapping_column_alias'
'/model/mysql/entity_mapping_type': 'test_mysql#entity_mapping_type'
'/model/mysql/entity_mapping_trait': 'test_mysql#entity_mapping_trait'
'/model/mysql/entity_mapping_property_proxy': 'test_mysql#entity_mapping_property_proxy'
'/model/mysql/transaction_commit': 'test_mysql#transaction_commit'
'/model/mysql/transaction_rollback': 'test_mysql#transaction_rollback'
'/model/mysql/transaction_isolationlevel/:level': 'test_mysql#transaction_isolationlevel'
'/model/postgres/direct_select_query': 'test_postgres#direct_select_query'
'/model/postgres/annotation_select_query': 'test_postgres#annotation_select_query'
'/model/postgres/direct_insert_query': 'test_postgres#direct_insert_query'
'/model/postgres/annotation_insert_query': 'test_postgres#annotation_insert_query'
'/model/postgres/direct_update_query': 'test_postgres#direct_update_query'
'/model/postgres/annotation_update_query': 'test_postgres#annotation_update_query'
'/model/postgres/direct_delete_query': 'test_postgres#direct_delete_query'
'/model/postgres/annotation_delete_query': 'test_postgres#annotation_delete_query'
'/model/postgres/transaction_commit': 'test_postgres#transaction_commit'
'/model/postgres/transaction_rollback': 'test_postgres#transaction_rollback'
'/model/postgres/entity_mapping1': 'test_mysql#entity_mapping1'
'/model/postgres/entity_mapping2': 'test_mysql#entity_mapping2'
'/model/postgres/entity_mapping_joined_table': 'test_mysql#entity_mapping_joined_table'
'/model/postgres/entity_mapping_column_alias': 'test_mysql#entity_mapping_column_alias'
'/model/postgres/entity_mapping_type': 'test_mysql#entity_mapping_type'
'/model/postgres/entity_mapping_trait': 'test_mysql#entity_mapping_trait'
'/model/postgres/entity_mapping_property_proxy': 'test_mysql#entity_mapping_property_proxy'
'/model/sqlite/direct_select_query': 'test_sqlite#direct_select_query'
'/model/sqlite/annotation_select_query': 'test_sqlite#annotation_select_query'
'/model/sqlite/direct_insert_query': 'test_sqlite#direct_insert_query'
'/model/sqlite/annotation_insert_query': 'test_sqlite#annotation_insert_query'
'/model/sqlite/direct_update_query': 'test_sqlite#direct_update_query'
'/model/sqlite/annotation_update_query': 'test_sqlite#annotation_update_query'
'/model/sqlite/direct_delete_query': 'test_sqlite#direct_delete_query'
'/model/sqlite/annotation_delete_query': 'test_sqlite#annotation_delete_query'
'/model/multiple_database_access': 'test_multiple_database#multiple_database_access'
'/model/error/undefined_driver': 'test_error_undefined_driver#undefined_driver'
'/model/error/undefined_config_file': 'test_error_undefined_config_file#undefined_config_file'
'/model/error/undefined_query': 'test_error_undefined_query#undefined_query'
'/model/error/undefined_query_mapping': 'test_error_undefined_query#undefined_query_mapping'
'/model/error/mysql/transaction_isolationlevel/:level': 'test_mysql#transaction_isolationlevel'
'/view/basic': 'test_view#basic'
'/view/basic/parts': 'test_view#basic_parts'
'/view/basic/encode/html': 'test_view#basic_encode_html'
'/view/basic/encode/javascript': 'test_view#basic_encode_javascript'
'/view/basic/encode/xml': 'test_view#basic_encode_xml'
'/view/error/service_class_noexist_and_model_class_noexist': 'test_no_service_class_no_model_class_in_view#test1'
