'/controller/ok': 'test_controller#test1'
'/controller/controller_method_noexist': 'test_controller#notFound'
'/controller/parent_class_method_access': 'test_child#test1'
'/service/ok': 'test_service#test1'
'/service/service_method_noexist': 'test_service#notFound'
'/service/service_class_noexist_and_model_class_noexist': "test_no_service_class_no_model_class#test1"
'/model/ok': 'test_model#test1'
'/model/service_class_noexist_and_model_class_exist': 'test_no_service_class_exist_model#test1'
'/model/mysql/direct_select_query': 'test_mysql#direct_select_query'
'/model/mysql/annotation_select_query': 'test_mysql#annotation_select_query'
'/model/mysql/direct_insert_query': 'test_mysql#direct_insert_query'
'/model/mysql/annotation_insert_query': 'test_mysql#annotation_insert_query'
'/model/mysql/direct_update_query': 'test_mysql#direct_update_query'
'/model/mysql/annotation_update_query': 'test_mysql#annotation_update_query'
'/model/mysql/direct_delete_query': 'test_mysql#direct_delete_query'
'/model/mysql/annotation_delete_query': 'test_mysql#annotation_delete_query'
'/model/mysql/yml': 'test_mysql_yml#direct_select_query'
'/model/mysql/transaction_commit': 'test_mysql#transaction_commit'
'/model/mysql/transaction_rollback': 'test_mysql#transaction_rollback'
'/model/postgres/direct_select_query': 'test_postgres#direct_select_query'
'/model/postgres/annotation_select_query': 'test_postgres#annotation_select_query'
'/model/postgres/direct_insert_query': 'test_postgres#direct_insert_query'
'/model/postgres/annotation_insert_query': 'test_postgres#annotation_insert_query'
'/model/postgres/direct_update_query': 'test_postgres#direct_update_query'
'/model/postgres/annotation_update_query': 'test_postgres#annotation_update_query'
'/model/postgres/direct_delete_query': 'test_postgres#direct_delete_query'
'/model/postgres/annotation_delete_query': 'test_postgres#annotation_delete_query'
'/model/sqlite/direct_select_query': 'test_sqlite#direct_select_query'
'/model/sqlite/annotation_select_query': 'test_sqlite#annotation_select_query'
'/model/sqlite/direct_insert_query': 'test_sqlite#direct_insert_query'
'/model/sqlite/annotation_insert_query': 'test_sqlite#annotation_insert_query'
'/model/sqlite/direct_update_query': 'test_sqlite#direct_update_query'
'/model/sqlite/annotation_update_query': 'test_sqlite#annotation_update_query'
'/model/sqlite/direct_delete_query': 'test_sqlite#direct_delete_query'
'/model/sqlite/annotation_delete_query': 'test_sqlite#annotation_delete_query'
'/model/multiple_database_access': 'test_multiple_database#multiple_database_access'
'/model/entity_mapping1': 'test_mysql#entity_mapping1'
'/model/entity_mapping2': 'test_mysql#entity_mapping2'
'/model/entity_mapping_joined_table': 'test_mysql#entity_mapping_joined_table'
'/model/entity_mapping_column_alias': 'test_mysql#entity_mapping_column_alias'
'/model/entity_mapping_type': 'test_mysql#entity_mapping_type'
'/model/entity_mapping_trait': 'test_mysql#entity_mapping_trait'
'/model/entity_mapping_property_proxy': 'test_mysql#entity_mapping_property_proxy'
